import mongoose from 'mongoose';

const wellnessSchema = new mongoose.Schema(
  {
    age: { type: Number, required: true },
    gender: { type: String, required: true },
    bmi: { type: Number, required: true },
    bmiStatus: { type: String, required: true },
    dietGoal: { type: String, required: true },
    foodPreferences: { type: String, required: true },
    fitnessLevel: { type: String, required: true },
    limitations: { type: String, default: 'None' }, // Optional
    dietPlan: { type: String, default: 'To be generated by AI' }, // Placeholder for AI diet plan
  },
  { collection: 'wellness' }
);

const Wellness = mongoose.model('Wellness', wellnessSchema);

export default Wellness;